# Generated by Django 2.2 on 2019-04-14 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(help_text='Enter the event name', max_length=300)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular event', primary_key=True, serialize=False)),
                ('fee', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('target_audience', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('faq', models.TextField()),
                ('tags', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('roll_no', models.BigIntegerField(unique=True)),
                ('phone_no', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
