# Generated by Django 2.2 on 2019-04-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_info',
            field=models.CharField(default='(not specified)', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='organisors',
            field=models.CharField(default='Multiple groups (not specified)', max_length=300),
        ),
    ]
