# Generated by Django 2.2 on 2019-04-17 18:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190415_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='comment_for_admin',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='organisors',
            field=models.CharField(default='(not specified)', max_length=300),
        ),
        migrations.AlterField(
            model_name='poll',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique poll id', primary_key=True, serialize=False),
        ),
    ]
