# Generated by Django 2.2 on 2019-04-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190417_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='user_id',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
