# Generated by Django 2.2 on 2019-04-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190414_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('cse', 'Computer Science & Engineering'), ('ece', 'Electronics & Communication Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('dd', 'Design'), ('bsbe', 'Biosciences & Bioengineering'), ('cl', 'Chemical Engineering'), ('cst', 'Chemical Science & Technology'), ('eee', 'Electronics & Electrical Engineering'), ('ma', 'Mathematics & Computing'), ('ph', 'Engineering Physics'), ('rt', 'Rural Technology'), ('hss', 'Humanities & Social Sciences'), ('enc', 'Centre for Energy'), ('env', 'Centre for Environment'), ('nt', 'Centre for Nanotechnology'), ('lst', 'Centre for Linguistic Science & Technology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.CharField(choices=[('btech', 'BTech'), ('mtech', 'MTech'), ('phd', 'PhD'), ('msc', 'MSc'), ('msr', 'MS-R'), ('ma', 'MA'), ('bdes', 'BDes'), ('mdes', 'MDes')], max_length=100),
        ),
    ]
