# Generated by Django 2.2 on 2019-04-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_poll_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='user_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
