# Generated by Django 2.2 on 2019-04-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
