# Generated by Django 2.2 on 2019-04-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mtech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_info',
            field=models.CharField(default='(not specified)', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='organisors',
            field=models.CharField(default='(not specified)', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='faq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(help_text=' (Press Ctrl to select multiple)', max_length=300),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_coming', models.PositiveIntegerField()),
                ('response_not_coming', models.PositiveIntegerField()),
                ('response_not_sure', models.PositiveIntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='invitees_btech',
            field=models.ManyToManyField(help_text=' (Press Ctrl to select multiple)', to='events.Btech'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitees_mtech',
            field=models.ManyToManyField(help_text=' (Press Ctrl to select multiple)', to='events.Mtech'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitees_phd',
            field=models.ManyToManyField(to='events.PhD'),
        ),
    ]
